### ISSUE TITLE
Login not possible with access control enabled

### ISSUE THREAD

**Issue by ugrupp** [ijsto/keystone-plugins#98]
When access control rules on the Keystone User object are present, they're evaluated in the oauth login flow.

I my case I'm setting certain conditions on `User.access.filter.query`. After logging in and being redirected from Auth0, the package checks if the given user exists, using `context.query`. As it's seemingly not using `context.sudo()`, this check respects the User query filter rules and returns nothing, even though the user might exist.

Versions:

"@keystone-6/auth": "^5.0.1",
"@keystone-6/core": "^3.1.3",
"keystone-6-oauth": "^0.5.7",

**Comment by ScottAgirs** [comment]
@ugrupp thank you for reporting.

This package is currently could you please provide the following:

- which version of Keystone are you using
- which version of `keystone-6-oauth` package
- how did you enable access control.

Cheers

**Comment by ugrupp** [comment]
Sorry, hit enter too early – I updated the issue description.

**Comment by ScottAgirs** [comment]
Haha, happens.

Ohh, I see. Indeed, we did this intentionally (removing the `sudo`), but perhaps this may be too limiting for these types of flows. 

Nice catch, would you be interested in submitting a PR?

Otherwise, I can take a look at this later this week, LMK 🙏🏼  🙂

**Comment by ScottAgirs** [comment]
Hey, @ugrupp, sorry for the delay, I have good news. 

Though, while I do recognize that this may not be an ideal solution, you may update your Keystone to `v4.0.x`, where this is now resolved with #112. 

Unless you're using `createContext` or `createRequestContext` the update is as simple as updating your keystone-related packages to their latest versions, nothing else needs be done.

If you are using, one of the above, please refer to the Keystone [release logs for V4.0.0](https://github.com/keystonejs/keystone/releases/tag/2022-12-06) for more information. 

Hope this helps, I will go ahead and close this for now, but feel free to open if it is impossible for you to upgrade to V4 at the moment.
